wandb_version: 1

headless:
  desc: null
  value: true
save_final_state:
  desc: null
  value: true
early_stop:
  desc: null
  value: false
action_freq:
  desc: null
  value: 24
init_state:
  desc: null
  value: has_pokedex_nballs.state
max_steps:
  desc: null
  value: 12000
print_rewards:
  desc: null
  value: true
save_video:
  desc: null
  value: false
fast_video:
  desc: null
  value: true
session_path:
  desc: null
  value: Sessions/ARS_Session_0409173251_105c5eaa_env2_1
gb_path:
  desc: null
  value: PokemonRed.gb
debug:
  desc: null
  value: false
reward_scale:
  desc: null
  value: 1
explore_weight:
  desc: null
  value: 0.5
battle_weight:
  desc: null
  value: 4
use_screen_explore:
  desc: null
  value: true
extra_buttons:
  desc: null
  value: false
sim_frame_dist:
  desc: null
  value: 2000000.0
_wandb:
  desc: null
  value:
    code_path: code/run_baseline_v2.py
    python_version: 3.11.8
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1712683976.376132
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 55
      3:
      - 14
      - 16
      - 22
      - 23
      - 35
      4: 3.11.8
      5: 0.15.12
      8:
      - 2
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: ARS
policy_class:
  desc: null
  value: <class 'sb3_contrib.ars.policies.ARSLinearPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 39996000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1712683976951006352
learning_rate:
  desc: null
  value: 0.02
tensorboard_log:
  desc: null
  value: Sessions/ARS_Session_0409173251_105c5eaa_env2_1
_last_obs:
  desc: null
  value: "OrderedDict([('badges', array([[0, 0, 0, 0, 0, 0, 0, 0],\n       [0, 0,\
    \ 0, 0, 0, 0, 0, 0],\n       [0, 0, 0, 0, 0, 0, 0, 0],\n       [0, 0, 0, 0, 0,\
    \ 0, 0, 0],\n       [0, 0, 0, 0, 0, 0, 0, 0],\n       [0, 0, 0, 0, 0, 0, 0, 0],\n\
    \       [0, 0, 0, 0, 0, 0, 0, 0],\n       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)),\
    \ ('events', array([[0, 0, 0, ..., 0, 0, 0],\n       [0, 0, 0, ..., 0, 0, 0],\n\
    \       [0, 0, 0, ..., 0, 0, 0],\n       ...,\n       [0, 0, 0, ..., 0, 0, 0],\n\
    \       [0, 0, 0, ..., 0, 0, 0],\n       [0, 0, 0, ..., 0, 0, 0]], dtype=int8)),\
    \ ('health', array([[1.],\n       [1.],\n       [1.],\n       [1.],\n       [1.],\n\
    \       [1.],\n       [1.],\n       [1.]])), ('level', array([[ 0.11971221,  0.23770263,\
    \  0.46177918,  0.81919157,  0.93964547,\n        -0.64299874,  0.98490333,  0.34098385],\n\
    \       [ 0.11971221,  0.23770263,  0.46177918,  0.81919157,  0.93964547,\n  \
    \      -0.64299874,  0.98490333,  0.34098385],\n       [ 0.11971221,  0.23770263,\
    \  0.46177918,  0.81919157,  0.93964547,\n        -0.64299874,  0.98490333,  0.34098385],\n\
    \       [ 0.11971221,  0.23770263,  0.46177918,  0.81919157,  0.93964547,\n  \
    \      -0.64299874,  0.98490333,  0.34098385],\n       [ 0.11971221,  0.23770263,\
    \  0.46177918,  0.81919157,  0.93964547,\n        -0.64299874,  0.98490333,  0.34098385],\n\
    \       [ 0.11971221,  0.23770263,  0.46177918,  0.81919157,  0.93964547,\n  \
    \      -0.64299874,  0.98490333,  0.34098385],\n       [ 0.11971221,  0.23770263,\
    \  0.46177918,  0.81919157,  0.93964547,\n        -0.64299874,  0.98490333,  0.34098385],\n\
    \       [ 0.11971221,  0.23770263,  0.46177918,  0.81919157,  0.93964547,\n  \
    \      -0.64299874,  0.98490333,  0.34098385]])), ('map', array([[[[0, 0, 0, ...,\
    \ 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0,\
    \ 0],\n         ...,\n         [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ...,\
    \ 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0]]],\n\n\n       [[[0, 0, 0, ...,\
    \ 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0,\
    \ 0],\n         ...,\n         [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ...,\
    \ 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0]]],\n\n\n       [[[0, 0, 0, ...,\
    \ 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0,\
    \ 0],\n         ...,\n         [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ...,\
    \ 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0]]],\n\n\n       ...,\n\n\n      \
    \ [[[0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 0],\n         ...,\n         [0, 0, 0, ..., 0, 0, 0],\n   \
    \      [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0]]],\n\n\n   \
    \    [[[0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 0],\n         ...,\n         [0, 0, 0, ..., 0, 0, 0],\n   \
    \      [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0]]],\n\n\n   \
    \    [[[0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0],\n         [0,\
    \ 0, 0, ..., 0, 0, 0],\n         ...,\n         [0, 0, 0, ..., 0, 0, 0],\n   \
    \      [0, 0, 0, ..., 0, 0, 0],\n         [0, 0, 0, ..., 0, 0, 0]]]], dtype=uint8)),\
    \ ('recent_actions', array([[0, 0, 0],\n       [0, 0, 0],\n       [0, 0, 0],\n\
    \       [0, 0, 0],\n       [0, 0, 0],\n       [0, 0, 0],\n       [0, 0, 0],\n\
    \       [0, 0, 0]], dtype=uint8)), ('screens', array([[[[  0,   0,   0, ..., \
    \  0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n         [  0,\
    \   0,   0, ...,   0,   0,   0],\n         ...,\n         [ 42, 153, 153, ...,\
    \   0,   0,   0],\n         [ 21,  76,  76, ...,   0,   0,   0],\n         [ 59,\
    \  76,  76, ...,   0,   0,   0]],\n\n        [[  0,   0,   0, ...,   0,   0, \
    \  0],\n         [  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0,\
    \ ...,   0,   0,   0],\n         ...,\n         [  0,   0,   0, ...,   0,   0,\
    \   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,  \
    \ 0, ...,   0,   0,   0]],\n\n        [[  0,   0,   0, ...,   0,   0,   0],\n\
    \         [  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,\
    \   0,   0,   0],\n         ...,\n         [  0,   0,   0, ...,   0,   0,   0],\n\
    \         [  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,\
    \   0,   0,   0]]],\n\n\n       [[[  0,   0,   0, ...,   0,   0,   0],\n     \
    \    [  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,\
    \   0,   0],\n         ...,\n         [ 42, 153, 153, ...,   0,   0,   0],\n \
    \        [ 21,  76,  76, ...,   0,   0,   0],\n         [ 59,  76,  76, ..., \
    \  0,   0,   0]],\n\n        [[  0,   0,   0, ...,   0,   0,   0],\n         [\
    \  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,\
    \   0],\n         ...,\n         [  0,   0,   0, ...,   0,   0,   0],\n      \
    \   [  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0, \
    \  0,   0]],\n\n        [[  0,   0,   0, ...,   0,   0,   0],\n         [  0,\
    \   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n\
    \         ...,\n         [  0,   0,   0, ...,   0,   0,   0],\n         [  0,\
    \   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,   0]]],\n\
    \n\n       [[[  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,\
    \   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n         ...,\n\
    \         [ 42, 153, 153, ...,   0,   0,   0],\n         [ 21,  76,  76, ...,\
    \   0,   0,   0],\n         [ 59,  76,  76, ...,   0,   0,   0]],\n\n        [[\
    \  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,\
    \   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n         ...,\n      \
    \   [  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0, \
    \  0,   0],\n         [  0,   0,   0, ...,   0,   0,   0]],\n\n        [[  0,\
    \   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n\
    \         [  0,   0,   0, ...,   0,   0,   0],\n         ...,\n         [  0,\
    \   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n\
    \         [  0,   0,   0, ...,   0,   0,   0]]],\n\n\n       ...,\n\n\n      \
    \ [[[  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0, \
    \  0,   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n         ...,\n  \
    \       [ 42, 153, 153, ...,   0,   0,   0],\n         [ 21,  76,  76, ...,  \
    \ 0,   0,   0],\n         [ 59,  76,  76, ...,   0,   0,   0]],\n\n        [[\
    \  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,\
    \   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n         ...,\n      \
    \   [  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0, \
    \  0,   0],\n         [  0,   0,   0, ...,   0,   0,   0]],\n\n        [[  0,\
    \   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n\
    \         [  0,   0,   0, ...,   0,   0,   0],\n         ...,\n         [  0,\
    \   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n\
    \         [  0,   0,   0, ...,   0,   0,   0]]],\n\n\n       [[[  0,   0,   0,\
    \ ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n      \
    \   [  0,   0,   0, ...,   0,   0,   0],\n         ...,\n         [ 42, 153, 153,\
    \ ...,   0,   0,   0],\n         [ 21,  76,  76, ...,   0,   0,   0],\n      \
    \   [ 59,  76,  76, ...,   0,   0,   0]],\n\n        [[  0,   0,   0, ...,   0,\
    \   0,   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n         [  0,  \
    \ 0,   0, ...,   0,   0,   0],\n         ...,\n         [  0,   0,   0, ..., \
    \  0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n         [  0,\
    \   0,   0, ...,   0,   0,   0]],\n\n        [[  0,   0,   0, ...,   0,   0, \
    \  0],\n         [  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0,\
    \ ...,   0,   0,   0],\n         ...,\n         [  0,   0,   0, ...,   0,   0,\
    \   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,  \
    \ 0, ...,   0,   0,   0]]],\n\n\n       [[[  0,   0,   0, ...,   0,   0,   0],\n\
    \         [  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,\
    \   0,   0,   0],\n         ...,\n         [ 42, 153, 153, ...,   0,   0,   0],\n\
    \         [ 21,  76,  76, ...,   0,   0,   0],\n         [ 59,  76,  76, ...,\
    \   0,   0,   0]],\n\n        [[  0,   0,   0, ...,   0,   0,   0],\n        \
    \ [  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,\
    \   0],\n         ...,\n         [  0,   0,   0, ...,   0,   0,   0],\n      \
    \   [  0,   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0, \
    \  0,   0]],\n\n        [[  0,   0,   0, ...,   0,   0,   0],\n         [  0,\
    \   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,   0],\n\
    \         ...,\n         [  0,   0,   0, ...,   0,   0,   0],\n         [  0,\
    \   0,   0, ...,   0,   0,   0],\n         [  0,   0,   0, ...,   0,   0,   0]]]],\
    \ dtype=uint8))])"
_last_episode_starts:
  desc: null
  value: '[ True  True  True  True  True  True  True  True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object
    at 0x7fe88c3b04d0>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: 'Dict(''badges'': MultiBinary(8), ''events'': MultiBinary(1400), ''health'':
    Box(0.0, 1.0, (1,), float32), ''level'': Box(-1.0, 1.0, (8,), float32), ''map'':
    Box(0, 255, (1, 48, 48), uint8), ''recent_actions'': MultiDiscrete([7 7 7]), ''screens'':
    Box(0, 255, (3, 72, 80), uint8))'
action_space:
  desc: null
  value: Discrete(7)
n_envs:
  desc: null
  value: 8
n_delta:
  desc: null
  value: 8
pop_size:
  desc: null
  value: 16
delta_std_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fe88c39a3e0>
n_eval_episodes:
  desc: null
  value: 1
n_top:
  desc: null
  value: 8
alive_bonus_offset:
  desc: null
  value: 0
zero_policy:
  desc: null
  value: 'True'
weights:
  desc: null
  value: tensor([0., 0., 0.,  ..., 0., 0., 0.])
processes:
  desc: null
  value: None
old_count:
  desc: null
  value: 0
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x7fe88c39a480>
policy:
  desc: null
  value: "ARSLinearPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (action_net): Sequential(\n    (0):\
    \ Linear(in_features=21022, out_features=7, bias=False)\n  )\n)"
n_params:
  desc: null
  value: 147154
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x7fe88c3adf10>
