wandb_version: 1

headless:
  desc: null
  value: true
save_final_state:
  desc: null
  value: true
early_stop:
  desc: null
  value: false
action_freq:
  desc: null
  value: 24
init_state:
  desc: null
  value: has_pokedex_nballs.state
max_steps:
  desc: null
  value: 220000
print_rewards:
  desc: null
  value: true
save_video:
  desc: null
  value: false
fast_video:
  desc: null
  value: true
session_path:
  desc: null
  value: Sessions/PPO_Session_0318082037_fba3c7c0_env2_1
gb_path:
  desc: null
  value: PokemonRed.gb
debug:
  desc: null
  value: false
reward_scale:
  desc: null
  value: 1.5
explore_weight:
  desc: null
  value: 3
use_screen_explore:
  desc: null
  value: true
extra_buttons:
  desc: null
  value: false
sim_frame_dist:
  desc: null
  value: 2000000.0
battle_weight:
  desc: null
  value: 3
_wandb:
  desc: null
  value:
    code_path: code/run_baseline_v2.py
    python_version: 3.11.7
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1710750043.475327
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 55
      3:
      - 14
      - 16
      - 22
      - 23
      - 35
      4: 3.11.7
      5: 0.15.12
      8:
      - 2
      - 5
      13: linux-x86_64
