wandb_version: 1

headless:
  desc: null
  value: true
save_final_state:
  desc: null
  value: false
early_stop:
  desc: null
  value: false
action_freq:
  desc: null
  value: 24
init_state:
  desc: null
  value: has_pokedex_nballs.state
max_steps:
  desc: null
  value: 22528
print_rewards:
  desc: null
  value: true
save_video:
  desc: null
  value: false
fast_video:
  desc: null
  value: true
session_path:
  desc: null
  value: Sessions/PPO_Session_0229164112_b9e2bc6a_env2_1
gb_path:
  desc: null
  value: PokemonRed.gb
debug:
  desc: null
  value: false
reward_scale:
  desc: null
  value: 1
explore_weight:
  desc: null
  value: 0.7
level_weight:
  desc: null
  value: 1.2
_wandb:
  desc: null
  value:
    code_path: code/RL_Training&Env/run_baseline_v2.py
    python_version: 3.11.6
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709224877.315229
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 55
      3:
      - 14
      - 16
      - 22
      - 23
      - 35
      4: 3.11.6
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
